"""Activity m13_a12_u1"""
NUMBEROFLOOPS = 0
NUMBEROFAPPLES = 2
while NUMBEROFLOOPS < 10:
    NUMBEROFAPPLES *= 2
    NUMBEROFAPPLES += NUMBEROFLOOPS
    NUMBEROFLOOPS -= 1
print("Number of apples: " + str(NUMBEROFAPPLES))
